# CI to build the Python code

on: [push, pull_request]

name: Python Continuous integration

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r robyn/test-requirements.txt
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Setup Rust part of the project
        run: |
          source $HOME/.cargo/env
          maturin build -i python --release --universal2 --out dist --no-sdist
          pip install --force-reinstall dist/robyn*.whl
      - name: Test with pytest
        run: |
          pytest ./integration_tests

  test-windows:
    name: Test on windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r robyn/test-requirements.txt
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Setup Rust part of the project
        run: |
          source $HOME/.cargo/env
          maturin build -i python --release --universal2 --out dist --no-sdist
          pip install --force-reinstall dist/robyn*.whl
      - name: Test with pytest
        run: |
          pytest ./integration_tests

  test-osx:
    name: Test on macos
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r robyn/test-requirements.txt
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Setup Rust part of the project
        run: |
          source $HOME/.cargo/env
          rustup target add aarch64-apple-darwin
          maturin build -i python --release --universal2 --out dist --no-sdist
          pip install --force-reinstall dist/robyn*.whl
      - name: Test with pytest
        run: |
          pytest ./integration_tests
